### ISSUE TITLE
VueJS 2.0

### ISSUE THREAD

**Issue by wouterNL** [hejianxian/vue-drag-and-drop-list#1]
Hi, 

I was wondering if you were gonna make it VueJS 2.0 compatible? 
Because currently it's not working(Uncaught TypeError: Cannot read property 'el' of undefined).

Thanks and keep up the good work!
- Wouter

**Comment by hejianxian** [comment]
I will, but need some time, may be next week.

Thank you for your attention.

**Comment by hejianxian** [comment]
Oh my God! 

In 2.0 directives have a greatly reduced scope of responsibility: they are now only used for applying low-level direct DOM manipulations.

https://github.com/vuejs/vue/issues/2873

If must support VueJS 2.0. I think it only can be a component. 

So! This is a troublesome thing. In the near future, I will not fix this problem, perhaps in the future will.

I'm very sorry!

**Comment by beeplin** [comment]
so sad hearing this...

**Comment by MeirionHughes** [comment]
Dam dude... the demo for this looks awesome. Such a shame it (I guess) doesn't work with Vue 2

**Comment by hejianxian** [comment]
@wouterNL @beeplin @MeirionHughes 

Not long ago, I made a new project called [vddl](https://github.com/hejianxian/vddl). 🤗 

> Vue components for modifying lists with the HTML5 drag & drop API.

I changed the directives into the components, and made it support Vuejs 1.0 and 2.0. 

[Documentation](http://hejx.space/vddl)
[Online Demo](http://hejx.space/vddl-demo)
