### ISSUE TITLE
Dynamically reate new Container

### ISSUE THREAD

**Issue by fourpixels** [hejianxian/vue-drag-and-drop-list#5]
How would I achieve this? :)

**Comment by hejianxian** [comment]
Hi! @fourpixels 

Maybe you can drag a new Container element to the left list, just like the [NestedContainers Demo](https://hejx.herokuapp.com/vue-dndl/#!/nested).

And you can look here [Demo Code](https://github.com/hejianxian/vue-drag-and-drop-list/blob/master/demo/src/views/nestedContainers.vue#L87-L104)

```js
{
    "type": "container",
    "id": 1,
    "columns": [
        {
          "type": "item",
          "id": "1"
        },
        {
          "type": "item",
          "id": "2"
        }
    ]
```

Drag the above data to the source data-list, it will auto create a new container element.

Hope this helps! 😄
