### ISSUE TITLE
I got something wrong.

### ISSUE THREAD

**Issue by jjljyn** [hejianxian/vue-drag-and-drop-list#6]
Hi!
Is there some easier simples?I'm a freshman and I got something wrong which i don't know why.Infect I just copied and pasted your code.Here is my code and debugs
This is my Main.vue .

HTML:
> <div v-for="(listName, list) in lists" class="col-md-4">
            <div class="panel panel-vue">
                <div class="panel-heading">
                    <h3 class="panel-title">List {{listName}}</h3>
                </div>
                <div class="panel-body">
                    <ul v-dnd-list :dnd-list="list" :dnd-horizontal-list="false">
                        <li v-dnd-draggable v-for="item in list"
                            :dnd-draggable="item"
                            :dnd-index="$index"
                            :dnd-data="list"
                            dnd-selected="selectedEvent"
                            dnd-effect-allowed="move"
                            dnd-dragstart="handleDragstart"
                            dnd-dragend="handleDragend"
                            dnd-canceled="handleCanceled"
                            v-bind:class="{'selected': selected === item}">
                            {{item.label}}
                        </li>
                        <li class="dndPlaceholder red">Custom placeholder</li>
                    </ul>
                </div>
            </div>

SCRIPT:
```
   import Vue from 'vue';
   import vueDragAndDropList from 'vue-drag-and-drop-list';

   Vue.use(vueDragAndDropList);

   export default {
    name: 'Main',
    data() {
      return  {
        "selected": null,
        "lists": {
          "A": [
            {
              "label": "Item A1",
              "disable": false
            },
            {
              "label": "Item A2"
            },
            {
              "label": "Item A3"
            },
            {
              "label": "Item A4"
            }
          ],
          "B": [
            {
              "label": "Item B1"
            },
            {
              "label": "Item B2"
            },
            {
              "label": "Item B3"
            },
            {
              "label": "Item B4"
            }
          ]
        }
      }
    }
  }

```

DEBUGS:

￼
<img width="1679" alt="screenshot" src="https://cloud.githubusercontent.com/assets/16191775/23548080/d9534172-0040-11e7-8d91-be52d93eb57a.png">

**Comment by hejianxian** [comment]
@jjljyn I'm sorry! it don't supported VueJS 2.0 😢

**Comment by jjljyn** [comment]
No wonder I got so many bugs.But I like your demo.It looks awesome. 👍

**Comment by hejianxian** [comment]
@jjljyn Thx!! 😃
