### ISSUE TITLE
这个现在支持vue2.0了嘛

### ISSUE THREAD

**Issue by lijiahao8898** [hejianxian/vue-drag-and-drop-list#7]
RT

**Comment by hejianxian** [comment]
@lijiahao8898 

抱歉，不支持！欢迎PR😁

**Comment by hejianxian** [comment]
@lijiahao8898 不过你可以根据里面的写法，用vue-component重新写一下！

**Comment by lijiahao8898** [comment]
和这个https://github.com/marceljuenemann/angular-drag-and-drop-lists 实现的功能是一样的嘛。本来用的是这个。但是现在要替换下。我看了下demo页面。好像差不多的。。。

**Comment by hejianxian** [comment]
是的！

主要是vue2.0，在指令这块取消了很多属性，所以没法直接迁移到vue2.0的，只能以vue-component的形式重写。

**Comment by hejianxian** [comment]
@lijiahao8898 

目前已经支持vue2.0 ，你可以查看[vddl](https://github.com/hejianxian/vddl)
