### ISSUE TITLE
Update to Vue 2

### ISSUE THREAD

**Issue by techjewel** [hejianxian/vue-drag-and-drop-list#9]
Hello @hejianxian,
This is an awesome package and I wanted to use this package for one of my upcoming projects. Do you have any plan to upgrade this soon? 
Also, if you need any helping hand, I would like to contribute with my little knowledge.

Thanks in advance.

**Comment by hejianxian** [comment]
@techjewel Thank you!

Then, shortly before, I made a new project called [vddl](https://github.com/hejianxian/vddl), I changed the directives into the components and made it support Vuejs 1.0 and 2.0. 

Hope this helps.😄

**Comment by techjewel** [comment]
It's awesome man! You should mention the new package in the readme so people can check your new awesome package. 

(y)
